image:
  file: Dockerfile

# List of tasks to run when starting a new workspace
tasks:
  - init: echo 'Running init script...' && setup-command
  - command: echo 'Running command...' && start-server

# Ports to expose on workspace startup
ports:
  - port: 8050
    onOpen: open-preview

# VSCode extensions to install
vscode:
  extensions:
    - esbenp.prettier-vscode