version: "3.9"

services:
  app:
    build:
      context: .
      args:
       - DEV=true
    ports:
      - "8050:8050"
    volumes:
      - ./MyGarage:/MyGarage
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8050"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=maris
      - DB_PASS=bv4811
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=maris
      - POSTGRES_PASSWORD=bv4811

volumes:
  dev-db-data: